version: "3"
services:
  app:
    container_name: node-app
    restart: always
    build: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - NODE_ENV="production"
    ports:
      - "3000:3000"
    depends_on: 
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./conduit:/data/db/
    ports:
      - "27017:27017"
secrets:
  AUTH_DOMAIN:
    external: true
  AUTH_SECRET:
    external: true
  STORAGE_HOST:
    external: true
