pipeline {
  //agent { label 'motf-unix-agent-01' }
  agent {
        docker { image 'node:16.13.1-alpine' }
    }

  environment{
    DEVELOPERS_EMAIL="faisal.nizam@devops.ae"
    GITHUB_REPO="git@github.com:faisalnizam/node-tf-k8s.git" 
  }

  stages {

    stage('Prepare'){
      parallel{
        stage('Checkout Code Repo'){
          steps{
            checkout scm
          }
        }
        stage('Prepare-Workspace'){
          steps{
            prepareWorkspace()
          }
        }
      }
    }


    stage("Build-Project"){
      steps{
          runBuild()
      }
    }

    stage("Run Test Tests"){
      steps{
        runTest()
      }
    }

    stage("Ask: Desploy to Staging"){
      agent none
        steps{
          script{
            env.DEPLOY_TO_DEV= input message: 'Approval is required',
              parameters: [
                choice(name: 'Do you want to deploy to Staging?', choices: 'no\nyes',
                    description: 'Choose "yes" if you want to deploy the DEV server')
              ]
          }
        }
    } // End of Deployment to Dev

      stage('Deploying To Staging Env'){
            when{
                environment name:'DEPLOY_TO_DEV', value:'yes'
            }
            steps{
                deployToServer("deploy-staging")
            }
        }

    stage("Ask: Deploy to Testing"){
      agent none
        steps{
          script{
            env.DEPLOY_TO_TEST= input message: 'Approval is required',
              parameters: [
                choice(name: 'Do you want to deploy to Test?', choices: 'no\nyes',
                    description: 'Choose "yes" if you want to deploy the Test server')
              ]
          }
        }
    } // End of Deployment to Dev

      stage('Deploy To Testing'){
            when{
                environment name:'DEPLOY_TO_TEST', value:'yes'
            }
            steps{
                deployToTesting("deploy-testing")
            }
        }



    stage("Ask: Deploy to Production"){
      agent none
        steps{
          script{
            env.DEPLOY_TO_PROD= input message: 'Approval is required',
              parameters: [
                choice(name: 'Do you want to deploy to Prod?', choices: 'no\nyes',
                    description: 'Choose "yes" if you want to deploy the Prod server')
              ]
          }
        }
    } // End of Deployment to Dev

      stage('Deploying To Production'){
            when{
                environment name:'DEPLOY_TO_PROD', value:'yes'
            }
            steps{
                deployToProduction("deploy-production")
            }
        }


} // End of Stages 


 post {
        always {
            cleanWs(cleanWhenNotBuilt: false,
                    deleteDirs: true,
                    disableDeferredWipeout: true,
                    notFailBuild: true,
                    patterns: [[pattern: '.gitignore', type: 'INCLUDE'],
                               [pattern: '.propsfile', type: 'EXCLUDE']])
        }
    }// End of Post Deployment Steps
    
} // End of Pipeline

def checkoutCode(){
  count=1
    retry(3){
      echo "Checkout the Code For MOTF Twill, Trial:${count}"
        git url:"${GITHUB_REPO}"
    }
}

def prepareWorkspace(){
    echo 'Check here if everything is ready to make a build'
    sh """"
        echo "Check If NOde Installed"
        node -v
        echo "Change to Directory" 
        cd app 
        npm install
        echo "Run Mongo Service as a Docker to test" 
        docker run -d  --name mongodb-docker  -p 27017:27017 mongo
    """
}


def runTest(){
    echo 'Run Php Tests on the Environment' 
    sh '''
       cd app 
       yarn test
    '''
}

def deployToServer(deployTo){
    echo "Deploying to : ${deployTo}"
    sh '''
        cd app
        yarn stop
       
        docker build -t registry.devops.ae:5050/node:latest node/
        docker push registry.devops.ae:5050/node:latest

    '''
}

def deployToProduction(deployTo){
    echo "Deploying to : ${deployTo}"
    sh '''
      echo "Deploying to Productiom
    '''
}

def deployToTesting(deployTo){
    echo "Deploying to : ${deployTo}"
    sh '''
      echo "Deploying to Testing
    '''
}


def runBuild(){
    echo "Building Project" 
    sh '''
       cd app
       env.NODE_ENV = "dev"
       yarn start & 
    '''
}


