apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-devops
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: faisal@devops.ae
    privateKeySecretRef:
      name: letsencrypt-devops
    solvers:
      - http01:
          ingress:
            class: nginx

